### PR TITLE
replace innerRef with forwardRef

### PR DESCRIPTION
**Pull request by mshwery**
This switches from `innerRef` to `React.forwardRef` support. Not 100% sure on the typing because we have to do some custom stuff to get the generic types to work right here...

### CODE REVIEW

**Comment by akleiner2** [comment]
What's up with all the `yarn.lock` changes?

**Comment by mshwery** [comment]
@akleiner2 honestly not sure where they came from! reverted that file.

**Comment by mshwery** [comment]
This will land as a breaking change

**Comment by mshwery** [comment]
Cutting an `@next` version of this to npm.

**Comment by akleiner2** [comment]
@mshwery is this good to take a stab at cutting over into `evergreen@v5`?

**Comment by akleiner2** [comment]
@mshwery is this good to take a stab at cutting over into `evergreen@v5`?

**Comment by mshwery** [comment]
@akleiner2 feel free to give it a spin! It should be available via `ui-box@next`

**Pull request merged**
